/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction} from 'ethers';
import {Contract, ContractTransaction, CallOverrides} from '@ethersproject/contracts';
import {BytesLike} from '@ethersproject/bytes';
import {Listener, Provider} from '@ethersproject/providers';
import {FunctionFragment, EventFragment, Result} from '@ethersproject/abi';

interface DataSourceInterface extends ethers.utils.Interface {
  functions: {
    'getData()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'getData', values?: void): string;

  decodeFunctionResult(functionFragment: 'getData', data: BytesLike): Result;

  events: {};
}

export class DataSource extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DataSourceInterface;

  functions: {
    getData(
      overrides?: CallOverrides
    ): Promise<{
      0: {
        balance: BigNumber;
        timestamp: BigNumber;
        0: BigNumber;
        1: BigNumber;
      }[];
    }>;
  };

  getData(
    overrides?: CallOverrides
  ): Promise<{balance: BigNumber; timestamp: BigNumber; 0: BigNumber; 1: BigNumber}[]>;

  staticCall: {
    getData(
      overrides?: CallOverrides
    ): Promise<{balance: BigNumber; timestamp: BigNumber; 0: BigNumber; 1: BigNumber}[]>;
  };

  filters: {};

  estimateGas: {
    getData(): Promise<BigNumber>;
  };

  populateTransaction: {
    getData(): Promise<PopulatedTransaction>;
  };
}
