/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LendingPoolMockInterface extends ethers.utils.Interface {
  functions: {
    "_pei()": FunctionFragment;
    "_userState(uint256)": FunctionFragment;
    "cleanUserState()": FunctionFragment;
    "getUserState(address)": FunctionFragment;
    "handleActionOnPei(address,address,uint256,uint256)": FunctionFragment;
    "setUserState(tuple[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "_pei", values?: void): string;
  encodeFunctionData(
    functionFragment: "_userState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cleanUserState", values?: void): string;
  encodeFunctionData(
    functionFragment: "getUserState",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "handleActionOnPei",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserState",
    values: [
      {
        underlyingAsset: string;
        stakedByUser: BigNumberish;
        totalStaked: BigNumberish;
      }[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "_pei", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_userState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cleanUserState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleActionOnPei",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserState",
    data: BytesLike
  ): Result;

  events: {
    "AssetConfigUpdated(address,uint256)": EventFragment;
    "AssetIndexUpdated(address,uint256)": EventFragment;
    "RewardsAccrued(address,uint256)": EventFragment;
    "UserIndexUpdated(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AssetConfigUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AssetIndexUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardsAccrued"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserIndexUpdated"): EventFragment;
}

export class LendingPoolMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LendingPoolMockInterface;

  functions: {
    _pei(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    _userState(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      underlyingAsset: string;
      stakedByUser: BigNumber;
      totalStaked: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }>;

    cleanUserState(overrides?: Overrides): Promise<ContractTransaction>;

    getUserState(
      user: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        underlyingAsset: string;
        stakedByUser: BigNumber;
        totalStaked: BigNumber;
        0: string;
        1: BigNumber;
        2: BigNumber;
      }[];
    }>;

    handleActionOnPei(
      user: string,
      asset: string,
      userBalance: BigNumberish,
      totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setUserState(
      userState: {
        underlyingAsset: string;
        stakedByUser: BigNumberish;
        totalStaked: BigNumberish;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  _pei(overrides?: CallOverrides): Promise<string>;

  _userState(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    underlyingAsset: string;
    stakedByUser: BigNumber;
    totalStaked: BigNumber;
    0: string;
    1: BigNumber;
    2: BigNumber;
  }>;

  cleanUserState(overrides?: Overrides): Promise<ContractTransaction>;

  getUserState(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    {
      underlyingAsset: string;
      stakedByUser: BigNumber;
      totalStaked: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }[]
  >;

  handleActionOnPei(
    user: string,
    asset: string,
    userBalance: BigNumberish,
    totalSupply: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setUserState(
    userState: {
      underlyingAsset: string;
      stakedByUser: BigNumberish;
      totalStaked: BigNumberish;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  staticCall: {
    _pei(overrides?: CallOverrides): Promise<string>;

    _userState(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      underlyingAsset: string;
      stakedByUser: BigNumber;
      totalStaked: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }>;

    cleanUserState(overrides?: Overrides): Promise<void>;

    getUserState(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      {
        underlyingAsset: string;
        stakedByUser: BigNumber;
        totalStaked: BigNumber;
        0: string;
        1: BigNumber;
        2: BigNumber;
      }[]
    >;

    handleActionOnPei(
      user: string,
      asset: string,
      userBalance: BigNumberish,
      totalSupply: BigNumberish,
      overrides?: Overrides
    ): Promise<void>;

    setUserState(
      userState: {
        underlyingAsset: string;
        stakedByUser: BigNumberish;
        totalStaked: BigNumberish;
      }[],
      overrides?: Overrides
    ): Promise<void>;
  };

  filters: {
    AssetConfigUpdated(asset: string | null, emission: null): EventFilter;

    AssetIndexUpdated(asset: string | null, index: null): EventFilter;

    RewardsAccrued(user: string | null, amount: null): EventFilter;

    UserIndexUpdated(
      user: string | null,
      asset: string | null,
      index: null
    ): EventFilter;
  };

  estimateGas: {
    _pei(): Promise<BigNumber>;
    _userState(arg0: BigNumberish): Promise<BigNumber>;
    cleanUserState(): Promise<BigNumber>;
    getUserState(user: string): Promise<BigNumber>;
    handleActionOnPei(
      user: string,
      asset: string,
      userBalance: BigNumberish,
      totalSupply: BigNumberish
    ): Promise<BigNumber>;
    setUserState(
      userState: {
        underlyingAsset: string;
        stakedByUser: BigNumberish;
        totalStaked: BigNumberish;
      }[]
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _pei(): Promise<PopulatedTransaction>;
    _userState(arg0: BigNumberish): Promise<PopulatedTransaction>;
    cleanUserState(): Promise<PopulatedTransaction>;
    getUserState(user: string): Promise<PopulatedTransaction>;
    handleActionOnPei(
      user: string,
      asset: string,
      userBalance: BigNumberish,
      totalSupply: BigNumberish
    ): Promise<PopulatedTransaction>;
    setUserState(
      userState: {
        underlyingAsset: string;
        stakedByUser: BigNumberish;
        totalStaked: BigNumberish;
      }[]
    ): Promise<PopulatedTransaction>;
  };
}
